### ISSUE TITLE
date not parsed correctly?

### ISSUE THREAD

**Issue by paragbaxi** [tenable/Tenable.io-SDK-for-Java#11]
Here's an issue I found where a date is apparently not being parsed correctly (when the month begins with '0'?). I have multiple instances of this, but only included two below as the stack traces are quite long.

2017-04-24T10:59:11.994 WARN  [com.tenable.io.api.workbenches.WorkbenchNessusFileParser] - Exception when parsing ReportItem child node 'plugin_modification_date' with value '2012/06/18'

java.text.ParseException: Failed to parse date "2012/06/18": Invalid number: /0

at com.fasterxml.jackson.databind.util.ISO8601Utils.parse(ISO8601Utils.java:302)

at com.fasterxml.jackson.databind.util.ISO8601DateFormat.parse(ISO8601DateFormat.java:52)

at com.tenable.io.api.workbenches.WorkbenchNessusFileParser$VulnerabilityObject.gotChild(WorkbenchNessusFileParser.java:353)

at com.tenable.io.api.workbenches.WorkbenchNessusFileParser$VulnerabilityObject.gotChild(WorkbenchNessusFileParser.java:235)

at com.tenable.io.core.utilities.NessusFileParser.handleStartElement(NessusFileParser.java:137)

at com.tenable.io.core.utilities.NessusFileParser.getNextPage(NessusFileParser.java:100)

at com.tenable.io.api.workbenches.WorkbenchNessusFileParser.getNextPage(WorkbenchNessusFileParser.java:117)

at com.tenable.io.api.workbenches.WorkbenchNessusFileParser.getNextVulnerabilitiesPage(WorkbenchNessusFileParser.java:104)

at com.tenable.io.api.workbenches.WorkbenchRef.getNextVulnerabilitiesPage(WorkbenchRef.java:70)

at com.tenable.io.examples.MyTest.testMyTest(MyTest.java:43)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)

at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)

at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)

at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)

at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)

at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)

at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)

at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)

at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)

at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)

at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)

at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)

at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)

at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)

at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)

at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.NumberFormatException: Invalid number: /0

at com.fasterxml.jackson.databind.util.ISO8601Utils.parseInt(ISO8601Utils.java:339)

at com.fasterxml.jackson.databind.util.ISO8601Utils.parse(ISO8601Utils.java:167)

... 55 more

2017-04-24T10:59:12.004 WARN  [com.tenable.io.api.workbenches.WorkbenchNessusFileParser] - Exception when parsing ReportItem child node 'plugin_publication_date' with value '1999/08/01'

java.text.ParseException: Failed to parse date "1999/08/01": Invalid number: /0

at com.fasterxml.jackson.databind.util.ISO8601Utils.parse(ISO8601Utils.java:302)

at com.fasterxml.jackson.databind.util.ISO8601DateFormat.parse(ISO8601DateFormat.java:52)

at com.tenable.io.api.workbenches.WorkbenchNessusFileParser$VulnerabilityObject.gotChild(WorkbenchNessusFileParser.java:356)

at com.tenable.io.api.workbenches.WorkbenchNessusFileParser$VulnerabilityObject.gotChild(WorkbenchNessusFileParser.java:235)

at com.tenable.io.core.utilities.NessusFileParser.handleStartElement(NessusFileParser.java:137)

at com.tenable.io.core.utilities.NessusFileParser.getNextPage(NessusFileParser.java:100)

at com.tenable.io.api.workbenches.WorkbenchNessusFileParser.getNextPage(WorkbenchNessusFileParser.java:117)

at com.tenable.io.api.workbenches.WorkbenchNessusFileParser.getNextVulnerabilitiesPage(WorkbenchNessusFileParser.java:104)

at com.tenable.io.api.workbenches.WorkbenchRef.getNextVulnerabilitiesPage(WorkbenchRef.java:70)

at com.tenable.io.examples.MyTest.testMyTest(MyTest.java:43)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)

at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)

at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)

at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)

at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)

at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)

at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)

at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)

at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)

at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)

at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)

at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)

at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)

at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)

at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)

at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.NumberFormatException: Invalid number: /0

at com.fasterxml.jackson.databind.util.ISO8601Utils.parseInt(ISO8601Utils.java:339)

at com.fasterxml.jackson.databind.util.ISO8601Utils.parse(ISO8601Utils.java:167)

... 55 more

**Comment by paragbaxi** [comment]
From David Schwalenberg:

As a follow up, my suggestion that the exception might be caused by a month beginning with '0' is not correct as I also observed the following stack trace:

2017-04-24T17:14:41.401 WARN  [com.tenable.io.api.workbenches.WorkbenchNessusFileParser] - Exception when parsing ReportItem child node 'plugin_publication_date' with value '1999/10/12'

java.text.ParseException: Failed to parse date "1999/10/12": Invalid number: /1

…
at com.fasterxml.jackson.databind.util.ISO8601Utils.parse(ISO8601Utils.java:302)

at com.fasterxml.jackson.databind.util.ISO8601DateFormat.parse(ISO8601DateFormat.java:52)

at com.tenable.io.api.workbenches.WorkbenchNessusFileParser$VulnerabilityObject.gotChild(WorkbenchNessusFileParser.java:356)

at com.tenable.io.api.workbenches.WorkbenchNessusFileParser$VulnerabilityObject.gotChild(WorkbenchNessusFileParser.java:235)

at com.tenable.io.core.utilities.NessusFileParser.handleStartElement(NessusFileParser.java:137)

at com.tenable.io.core.utilities.NessusFileParser.handleStartElement(NessusFileParser.java:136)

…
at com.tenable.io.core.utilities.NessusFileParser.getNextPage(NessusFileParser.java:100)

at com.tenable.io.api.workbenches.WorkbenchNessusFileParser.getNextPage(WorkbenchNessusFileParser.java:117)

at com.tenable.io.api.workbenches.WorkbenchNessusFileParser.getNextAssetPage(WorkbenchNessusFileParser.java:92)

at com.tenable.io.api.workbenches.WorkbenchRef.getNextAssetPage(WorkbenchRef.java:50)

at com.tenable.io.examples.MyTest.testMyTest(MyTest.java:44)

…
Caused by: java.lang.NumberFormatException: Invalid number: /1

…
at com.fasterxml.jackson.databind.util.ISO8601Utils.parseInt(ISO8601Utils.java:339)

at com.fasterxml.jackson.databind.util.ISO8601Utils.parse(ISO8601Utils.java:167)

... 56 more

**Comment by pierresc** [comment]
The problem is we are expecting an ISO8601 date but this one is not,
 the slashes should be dashes (https://en.wikipedia.org/wiki/ISO_8601). I will add logic to handle both.

**Comment by pierresc** [comment]
I've relaxed the parsing rules to allow '/' in dates.
