### ISSUE TITLE
Not working with newest version from api

### ISSUE THREAD

**Issue by dasbaumwolltier** [tenable/Tenable.io-SDK-for-Java#52]
For example in the classes `ScanHostDetails` and `ScanHostDetailsInfo` there are single objects:
```java
String operatingSystem;
and
ScanHostVulnerability vulnerabilities;
```

respectively. The corresponding JSON properties are an array though:

```json
"operating-system": [
  "linux",
  "windows"
]
---
"vulnerabilities" : [
 {
    ...
  },
  {
    ...
  }
]
```

This causes Jackson to throw an `MismatchedInputException`:
```exception
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (String)"{"info":{"mac-address":null,"host-fqdn":"[censored]","host-ip":"[censored]","operating-system":["Linux Kernel","Linux Kernel","Linux Kernel"],"host_end":"Wed Jan 01 12:00:00 2019","host_start":"Wed Jan 01 11:00:00 2019"},"vulnerabilities":[{"count":8,"host_id":[censored],"hostname":"[censored]","plugin_family":"Port scanners","plugin_id":11219,"plugin_name":"Nessus S"[truncated 2044 chars]; line: 1, column: 161] (through reference chain: com.tenable.io.api.scans.models.ScanHostDetails["info"]->com.tenable.io.api.scans.models.ScanHostDetailsInfo["operating-system"])
	at com.tenable.io.core.utilities.JsonHelper.fromJson(JsonHelper.java:112)
	at com.tenable.io.core.services.HttpFuture.getAsType(HttpFuture.java:160)
	at com.tenable.io.api.scans.ScansApi.hostDetails(ScansApi.java:323)
	at com.tenable.io.api.scans.ScansApi$hostDetails$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at ideaGroovyConsole.run(ideaGroovyConsole.groovy:7)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)
	at groovy.lang.GroovyShell.run(GroovyShell.java:507)
	at groovy.lang.GroovyShell.run(GroovyShell.java:486)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:169)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at console.run(console.groovy:11)
	at groovy.ui.GroovyMain.processReader(GroovyMain.java:576)
	at groovy.ui.GroovyMain.processFiles(GroovyMain.java:485)
	at groovy.ui.GroovyMain.run(GroovyMain.java:327)
	at groovy.ui.GroovyMain.process(GroovyMain.java:315)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:134)
	at groovy.ui.GroovyMain.main(GroovyMain.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:116)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:66)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (String)"{"info":{"mac-address":null,"host-fqdn":"[censored]","host-ip":"[censored]","operating-system":["Linux Kernel","Linux Kernel","Linux Kernel"],"host_end":"Wed Jan 01 12:00:00 2019","host_start":"Wed Jan 01 11:00:00 2019"},"vulnerabilities":[{"count":8,"host_id":[censored],"hostname":"[censored]","plugin_family":"Port scanners","plugin_id":11219,"plugin_name":"Nessus S"[truncated 2044 chars]; line: 1, column: 161] (through reference chain: com.tenable.io.api.scans.models.ScanHostDetails["info"]->com.tenable.io.api.scans.models.ScanHostDetailsInfo["operating-system"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:675)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:40)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:10)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at com.tenable.io.core.utilities.JsonHelper.fromJson(JsonHelper.java:110)
```

I do not know if there is a problem also anywhere else, because I only use a small subset of the API.

**Comment by tenableAndrew** [comment]
This should be resolved in #54 and in release v1.3.1
