### ISSUE TITLE
com.tenable.io.core.exceptions.TenableIoException: API is not available

### ISSUE THREAD

**Issue by scanguskhan** [tenable/Tenable.io-SDK-for-Java#60]
Running into an issue trying to run a simple scan...

I use client.getScanHelper().getScansByName(scanName) to a get a valid scan (a scan that works in the UI) 

then run 

scan.launch();  

Output is 

com.tenable.io.core.exceptions.TenableIoException: API is not available

	at com.tenable.io.core.services.HttpFuture.getResponse(HttpFuture.java:331)
	at com.tenable.io.core.services.HttpFuture.getAsString(HttpFuture.java:239)
	at com.tenable.io.core.services.HttpFuture.getAsJson(HttpFuture.java:224)
	at com.tenable.io.core.services.HttpFuture.getAsType(HttpFuture.java:177)
	at com.tenable.io.api.scans.ScansApi.create(ScansApi.java:141)
	at com.tenable.io.api.scans.ScanHelper.createScan(ScanHelper.java:81)

**Comment by scanguskhan** [comment]
I just realized the  API is not really supported in Nessus Professional. Unfortunately,  that's a disqualifier for us. Closing this out.
